<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCJw8TW0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCJw8TW0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCJw8TW0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCJw8TW0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCJw8TW0\App_KernelDevDebugContainer([
    'container.build_hash' => 'CJw8TW0',
    'container.build_id' => 'a1705a13',
    'container.build_time' => 1681459000,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCJw8TW0');
