<?php

namespace ContainerCJw8TW0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A5UGK0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a5UGK_0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a5UGK_0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AvisController::delete' => ['privates', '.service_locator.uMrgoMM', 'get_ServiceLocator_UMrgoMMService', true],
            'App\\Controller\\AvisController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AvisController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AvisController::show' => ['privates', '.service_locator.FLA_F9f', 'get_ServiceLocator_FLAF9fService', true],
            'App\\Controller\\RestaurantController::delete' => ['privates', '.service_locator.Hc8H.Su', 'get_ServiceLocator_Hc8H_SuService', true],
            'App\\Controller\\RestaurantController::edit' => ['privates', '.service_locator.VZwM3sL', 'get_ServiceLocator_VZwM3sLService', true],
            'App\\Controller\\RestaurantController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\RestaurantController::indexClient' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\RestaurantController::new' => ['privates', '.service_locator.MYMgWQW', 'get_ServiceLocator_MYMgWQWService', true],
            'App\\Controller\\RestaurantController::show' => ['privates', '.service_locator.DtJYimM', 'get_ServiceLocator_DtJYimMService', true],
            'App\\Controller\\RestaurantController::showClient' => ['privates', '.service_locator.DtJYimM', 'get_ServiceLocator_DtJYimMService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AvisController:delete' => ['privates', '.service_locator.uMrgoMM', 'get_ServiceLocator_UMrgoMMService', true],
            'App\\Controller\\AvisController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AvisController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AvisController:show' => ['privates', '.service_locator.FLA_F9f', 'get_ServiceLocator_FLAF9fService', true],
            'App\\Controller\\RestaurantController:delete' => ['privates', '.service_locator.Hc8H.Su', 'get_ServiceLocator_Hc8H_SuService', true],
            'App\\Controller\\RestaurantController:edit' => ['privates', '.service_locator.VZwM3sL', 'get_ServiceLocator_VZwM3sLService', true],
            'App\\Controller\\RestaurantController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\RestaurantController:indexClient' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\RestaurantController:new' => ['privates', '.service_locator.MYMgWQW', 'get_ServiceLocator_MYMgWQWService', true],
            'App\\Controller\\RestaurantController:show' => ['privates', '.service_locator.DtJYimM', 'get_ServiceLocator_DtJYimMService', true],
            'App\\Controller\\RestaurantController:showClient' => ['privates', '.service_locator.DtJYimM', 'get_ServiceLocator_DtJYimMService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AvisController::delete' => '?',
            'App\\Controller\\AvisController::index' => '?',
            'App\\Controller\\AvisController::new' => '?',
            'App\\Controller\\AvisController::show' => '?',
            'App\\Controller\\RestaurantController::delete' => '?',
            'App\\Controller\\RestaurantController::edit' => '?',
            'App\\Controller\\RestaurantController::index' => '?',
            'App\\Controller\\RestaurantController::indexClient' => '?',
            'App\\Controller\\RestaurantController::new' => '?',
            'App\\Controller\\RestaurantController::show' => '?',
            'App\\Controller\\RestaurantController::showClient' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AvisController:delete' => '?',
            'App\\Controller\\AvisController:index' => '?',
            'App\\Controller\\AvisController:new' => '?',
            'App\\Controller\\AvisController:show' => '?',
            'App\\Controller\\RestaurantController:delete' => '?',
            'App\\Controller\\RestaurantController:edit' => '?',
            'App\\Controller\\RestaurantController:index' => '?',
            'App\\Controller\\RestaurantController:indexClient' => '?',
            'App\\Controller\\RestaurantController:new' => '?',
            'App\\Controller\\RestaurantController:show' => '?',
            'App\\Controller\\RestaurantController:showClient' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
